### PR TITLE
Wallet Settings Page Changes

### PR DESCRIPTION
**Pull request by jalvarezh1994**

### CODE REVIEW

**Comment by detroitpro** [comment]
feat: download keystore file in device
feat: wallet settings top menu is now functional

**Review by detroitpro — APPROVED** [review]
Looks good. Let's try to keep PRs only completing one issue.

closes #61

**Comment by cafadev** [comment]
Can you take a look at the conflicting files? @jalvarezh1994

**Comment by jalvarezh1994** [comment]
> Can you take a look at the conflicting files? @jalvarezh1994

On it

**Pull request merged**
